flags: {}
packages:
- '.'
extra-deps:
- HDBC-2.4.0.1
- HDBC-postgresql-2.3.2.3
- HDBC-session-0.1.0.0
- attoparsec-conduit-1.1.0
- names-th-0.1.0.1
- persistable-record-0.1.0.1
- regular-0.3.4.4
- regular-xmlpickler-0.2
- relational-query-0.6.0.0
- relational-query-HDBC-0.1.0.1
- relational-schemas-0.1.0.2
- sockaddr-0.0.0
- sql-words-0.1.3.1
- static-hash-0.0.1
- wai-app-file-cgi-3.0.8
resolver: lts-3.6
